#!/bin/bash
# Quick setup for Telegram bot secrets in Supabase Vault

PROJECT_REF="gykgrrjiqkucstcyrgxp"
DASHBOARD_URL="https://supabase.com/dashboard/project/$PROJECT_REF/settings/vault"

echo "🤖 Telegram Bot Setup for Paper Trading Bot"
echo "==========================================="
echo ""
echo "✅ Telegram Bot Created: @TMTMarketscanner_bot"
echo "Token: 8713960457:AAG7S--YR6rtB75LJ1WWZwRBTvt-NJB3u68"
echo ""
echo "Step 1: Get Your Telegram Chat ID"
echo "  • Open Telegram"
echo "  • Message @userinfobot"
echo "  • Copy the ID it sends back"
echo ""
read -p "Enter your Telegram Chat ID: " CHAT_ID

if [ -z "$CHAT_ID" ]; then
  echo "❌ Chat ID is required"
  exit 1
fi

echo ""
echo "Step 2: Add Secrets to Supabase Vault"
echo "  Go to: $DASHBOARD_URL"
echo ""
echo "Click 'New Secret' and add these two:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Secret 1:"
echo "  Name: telegram_bot_token"
echo "  Value: 8713960457:AAG7S--YR6rtB75LJ1WWZwRBTvt-NJB3u68"
echo ""
echo "Secret 2:"
echo "  Name: telegram_chat_id"
echo "  Value: $CHAT_ID"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 3: Also add these project secrets (for cron jobs):"
echo ""
echo "Secret 3:"
echo "  Name: market_sniper_project_url"
echo "  Value: https://$PROJECT_REF.supabase.co"
echo ""
echo "Secret 4:"
echo "  Name: market_sniper_anon_jwt"
echo "  Value: (Get from Settings → API → anon public key)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 4: After adding secrets, verify they're set:"
echo "  supabase db query \"SELECT name FROM vault.decrypted_secrets LIMIT 10;\" --linked"
echo ""
echo "🚀 Then test the health check:"
echo "  curl -X POST https://$PROJECT_REF.supabase.co/functions/v1/bot-health-check \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"test\": true}'"
echo ""
