import type { AlertFeedItem, ShadowTradePosition } from "./types";

export const sampleAlerts: AlertFeedItem[] = [
  {
    id: "sample-alert-reliance",
    instrument_id: "sample-instrument-reliance",
    symbol: "RELIANCE",
    exchange: "NSE",
    instrument_name: "Reliance Industries",
    alert_type: "liquidity_trap",
    direction: "bearish",
    title: "RELIANCE swept previous day high",
    thesis: "Price swept previous day high on elevated volume and faded back toward VWAP.",
    trigger_price: 2919,
    current_price: 2924.5,
    swept_level: 2919,
    swept_level_name: "Previous Day High",
    volume_multiplier: 1.74,
    conviction_score: 82,
    score_factors: [
      { name: "Daily trend", score: 24, state: "aligned" },
      { name: "VWAP distance", score: 18, state: "extended" },
      { name: "Volume expansion", score: 22, state: "confirmed" },
      { name: "Level quality", score: 18, state: "clean sweep" },
    ],
    timeframe_alignment: {
      daily: "uptrend",
      intraday: "failed breakout",
      vwap: "extended above",
    },
    market_session: "regular",
    status: "active",
    detected_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sample-alert-hdfc",
    instrument_id: "sample-instrument-hdfc",
    symbol: "HDFCBANK",
    exchange: "NSE",
    instrument_name: "HDFC Bank",
    alert_type: "liquidity_trap",
    direction: "bullish",
    title: "HDFCBANK reclaimed previous day low",
    thesis: "Opening drive flushed below prior day low, absorbed volume, and reclaimed VWAP.",
    trigger_price: 1518.25,
    current_price: 1548.3,
    swept_level: 1518.25,
    swept_level_name: "Previous Day Low",
    volume_multiplier: 1.58,
    conviction_score: 76,
    score_factors: [
      { name: "Daily trend", score: 18, state: "neutral" },
      { name: "VWAP reclaim", score: 24, state: "confirmed" },
      { name: "Volume expansion", score: 20, state: "confirmed" },
      { name: "Level quality", score: 14, state: "wick rejection" },
    ],
    timeframe_alignment: {
      daily: "range support",
      intraday: "reclaim",
      vwap: "above VWAP",
    },
    market_session: "regular",
    status: "active",
    detected_at: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
  },
];

export const sampleTrades: ShadowTradePosition[] = [
  {
    id: "sample-trade-reliance",
    user_id: "sample-user",
    alert_id: "sample-alert-reliance",
    instrument_id: "sample-instrument-reliance",
    symbol: "RELIANCE",
    exchange: "NSE",
    instrument_name: "Reliance Industries",
    side: "short",
    quantity: 10,
    entry_price: 2924.5,
    current_price: 2910.2,
    exit_price: null,
    entry_reason: "Liquidity Trap Alert paper trade",
    exit_reason: null,
    status: "open",
    opened_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    closed_at: null,
    unrealized_pnl: 143,
    pnl_percent: 0.49,
  },
];
