create schema if not exists extensions;
create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists supabase_vault with schema vault;

create table if not exists public.bot_settings (
  id integer primary key generated by default as identity,
  trading_enabled boolean not null default true,
  kill_switch_reason text,
  paper_capital numeric not null default 100000,
  daily_drawdown_cap numeric not null default 3000,
  last_heartbeat_at timestamptz,
  updated_at timestamptz not null default now()
);

create or replace function public.bot_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists bot_settings_set_updated_at on public.bot_settings;
create trigger bot_settings_set_updated_at
before update on public.bot_settings
for each row execute function public.bot_set_updated_at();

insert into public.bot_settings (id)
values (1)
on conflict (id) do nothing;

alter sequence public.bot_settings_id_seq restart with 2;

alter table public.bot_settings enable row level security;

grant select on public.bot_settings to anon, authenticated;

drop policy if exists "Public can read bot settings" on public.bot_settings;
create policy "Public can read bot settings"
on public.bot_settings for select
to anon, authenticated
using (true);

do $$
begin
  begin
    alter publication supabase_realtime add table public.bot_settings;
  exception
    when duplicate_object then
      null;
  end;
end;
$$;

select cron.unschedule(jobid)
from cron.job
where jobname = 'bot-heartbeat-every-minute';

select cron.schedule(
  'bot-heartbeat-every-minute',
  '*/1 * * * *',
  $$
  select net.http_post(
    url := coalesce(
      (select decrypted_secret from vault.decrypted_secrets where name = 'bot_project_url' limit 1),
      (select decrypted_secret from vault.decrypted_secrets where name = 'market_sniper_project_url' limit 1)
    ) || '/functions/v1/bot-heartbeat',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || coalesce(
        (select decrypted_secret from vault.decrypted_secrets where name = 'bot_anon_jwt' limit 1),
        (select decrypted_secret from vault.decrypted_secrets where name = 'market_sniper_anon_jwt' limit 1)
      )
    ),
    body := jsonb_build_object('scheduled_at', now())
  ) as request_id;
  $$
);
